### PR TITLE
refactor!: remove logging

### PR DESCRIPTION
**Pull request by Pscheidl**
The log crate is now a dev dependency. Logging
only happens when running in the test scope - `cfg(test)`. This eliminates the risk of logging being secretely enabled by other dependencies, revealing potential secrets.

### CODE REVIEW

**Comment by Pscheidl** [comment]
Based on https://github.com/Xuanwo/serde-env/discussions/34

**Comment by Pscheidl** [comment]
@Xuanwo looks like two jobs timed out before a suitable runner was a CV available. Would you mind restarting them ? TY.

**Comment by Xuanwo** [comment]
Hi, I feel like we can remove those log entirely.

**Comment by Pscheidl** [comment]
That's the best solution really. I'll do that.

**Review by Xuanwo — APPROVED** [review]
Perfect, thanks!

**Pull request merged**
