### PR TITLE
Fix override key bug

### PR DESCRIPTION
**Pull request by kgtkr**
Fixed a bug where inserting in the order `a_b=x`, `a=y` overwrote keys.
I also added a test.

This is the log of the added test before the fix.
```
$ cargo test 
   Compiling serde-env v0.0.2 (/Volumes/Develop/github/kgtkr/serde-env)
    Finished test [unoptimized + debuginfo] target(s) in 0.69s
     Running unittests src/lib.rs (target/debug/deps/serde_env-26d62904ea096b0f)

running 11 tests
test de::tests::test_from_env_alias ... ignored
test value::tests::test_get ... ok
test value::tests::test_flatten ... ok
test value::tests::test_push ... FAILED
test de::tests::test_ported_from_envy ... ok
test de::tests::test_from_env_flat_upper ... ok
test de::tests::test_from_env_flat_upper_with_default ... ok
test de::tests::test_from_env_as_map ... ok
test de::tests::test_from_env_flat_with_default ... ok
test de::tests::test_from_env_flat ... ok
test de::tests::test_from_env ... ok

failures:

---- value::tests::test_push stdout ----
thread 'value::tests::test_push' panicked at 'assertion failed: `(left == right)`
  left: `{"a": Hello, Earth!}`,
 right: `{"a": ["Hello, Earth!", {"b": {"c": {"d": Hello, World!, "e": Hello, Mars!}, "f": Hello, Moon!}}]}`', src/value.rs:163:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    value::tests::test_push

test result: FAILED. 9 passed; 1 failed; 1 ignored; 0 measured; 0 filtered out; finished in 0.01s

error: test failed, to rerun pass '--lib'
```

### CODE REVIEW

**Comment by Xuanwo** [comment]
Nice!

**Comment by Xuanwo** [comment]
Seems this PR will also fix https://github.com/Xuanwo/serde-env/issues/2?

**Comment by kgtkr** [comment]
I think it will probably be fixed (didn't check the issue)

**Comment by Xuanwo** [comment]
Thanks for you contribution!

**Pull request merged**
